# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate autocorrelation function at lag 1
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' ac_1(x)
#'
ac_1 <- function(x) {
    .Call(`_tsCeatures_ac_1`, x)
}

#' Calculate autocorrelation function at lag 2
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' ac_2(x)
#'
ac_2 <- function(x) {
    .Call(`_tsCeatures_ac_2`, x)
}

#' Calculate number of crossing points
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' crossing_points(x)
#'
crossing_points <- function(x) {
    .Call(`_tsCeatures_crossing_points`, x)
}

#' Calculate lumpiness which is the variance of tiled window variances
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references  Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' lumpiness(x)
#'
lumpiness <- function(x) {
    .Call(`_tsCeatures_lumpiness`, x)
}

#' Calculate Quantile 5
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_5(x)
#'
quantile_5 <- function(x) {
    .Call(`_tsCeatures_quantile_5`, x)
}

#' Calculate Quantile 10
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_10(x)
#'
quantile_10 <- function(x) {
    .Call(`_tsCeatures_quantile_10`, x)
}

#' Calculate Quantile 25
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_25(x)
#'
quantile_25 <- function(x) {
    .Call(`_tsCeatures_quantile_25`, x)
}

#' Calculate Quantile 75
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_75(x)
#'
quantile_75 <- function(x) {
    .Call(`_tsCeatures_quantile_75`, x)
}

#' Calculate Quantile 90
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_90(x)
#'
quantile_90 <- function(x) {
    .Call(`_tsCeatures_quantile_90`, x)
}

#' Calculate Quantile 95
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_95(x)
#'
quantile_95 <- function(x) {
    .Call(`_tsCeatures_quantile_95`, x)
}

#' Calculate stability which is the variance of tiled window means
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references  Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' stability(x)
#'
stability <- function(x) {
    .Call(`_tsCeatures_stability`, x)
}

