# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate autocorrelation function at lag 1
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' ac_1(x)
#'
ac_1 <- function(x) {
    .Call('_tsCeatures_ac_1', PACKAGE = 'tsCeatures', x)
}

#' Calculate autocorrelation function at lag 2
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' ac_2(x)
#'
ac_2 <- function(x) {
    .Call('_tsCeatures_ac_2', PACKAGE = 'tsCeatures', x)
}

#' Calculate number of crossing points
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' crossing_points(x)
#'
crossing_points <- function(x) {
    .Call('_tsCeatures_crossing_points', PACKAGE = 'tsCeatures', x)
}

#' Calculate lumpiness which is the variance of tiled window variances
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references  Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' lumpiness(x)
#'
lumpiness <- function(x) {
    .Call('_tsCeatures_lumpiness', PACKAGE = 'tsCeatures', x)
}

#' Calculate proportion of points above the mean, as per binarize_mean from the MATLAB toolbox \code{hctsa}
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' prop_above_mean(x)
#'
prop_above_mean <- function(x) {
    .Call('_tsCeatures_prop_above_mean', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 5
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_5(x)
#'
quantile_5 <- function(x) {
    .Call('_tsCeatures_quantile_5', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 10
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_10(x)
#'
quantile_10 <- function(x) {
    .Call('_tsCeatures_quantile_10', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 25
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_25(x)
#'
quantile_25 <- function(x) {
    .Call('_tsCeatures_quantile_25', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 75
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_75(x)
#'
quantile_75 <- function(x) {
    .Call('_tsCeatures_quantile_75', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 90
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_90(x)
#'
quantile_90 <- function(x) {
    .Call('_tsCeatures_quantile_90', PACKAGE = 'tsCeatures', x)
}

#' Calculate Quantile 95
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' quantile_95(x)
#'
quantile_95 <- function(x) {
    .Call('_tsCeatures_quantile_95', PACKAGE = 'tsCeatures', x)
}

#' Calculate stability which is the variance of tiled window means
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references  Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' stability(x)
#'
stability <- function(x) {
    .Call('_tsCeatures_stability', PACKAGE = 'tsCeatures', x)
}

#' Calculate numerator of the trev function from the MATLAB toolbox \code{hctsa}
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' trev_num(x)
#'
trev_num <- function(x) {
    .Call('_tsCeatures_trev_num', PACKAGE = 'tsCeatures', x)
}

#' Calculate proportion of length that walker crosses time series, as per PH_Walker_prop_01_sw_propcross from the MATLAB toolbox \code{hctsa}
#'
#' @param x a numerical time-series input vector
#' @return scalar value
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @references  Rob Hyndman, Yanfei Kang, Pablo Montero-Manso, Thiyanga Talagala, Earo Wang, Yangzhuoran Yang and Mitchell O'Hara-Wild (2020). tsfeatures: Time Series Feature Extraction. R package version 1.0.2. https://CRAN.R-project.org/package=tsfeatures
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' walker_propcross(x)
#'
walker_propcross <- function(x) {
    .Call('_tsCeatures_walker_propcross', PACKAGE = 'tsCeatures', x)
}

